version: 2
jobs:
  build:
    docker:
      - image: microsoft/aspnetcore-build:2.0
    steps:
      - checkout
      - run: find .
      - run: dotnet restore src/GlobalX.Hypermedia.AspNetCore.sln
      - run: dotnet pack src/GlobalX.Hypermedia.AspNetCore.sln --include-source --include-symbols -o ../../nuget      
      - run: 
          working_directory: ./
          command: echo 'dotnet nuget push -k "$NUGET_KEY" -s https://api.nuget.org/v3/index.json ./nuget/GlobalX.Hypermedia.AspNetCore*.nupkg | bash'