version: 2
jobs:
  build:
    docker:
      - image: microsoft/aspnetcore-build:2.0
    steps:
      - checkout
      - run: find .
      - run: dotnet restore src/GlobalX.Hypermedia.AspNetCore/GlobalX.Hypermedia.AspNetCore.sln
      - run: dotnet pack src/GlobalX.Hypermedia.AspNetCore/GlobalX.Hypermedia.AspNetCore.sln --include-source --include-symbols -o ../../nuget