version: 2
jobs:
  build:
    docker:
      - image: microsoft/aspnetcore-build:2.0
    steps:
      - checkout
      - run: find .
      - run: dotnet restore
      - run: dotnet pack src/GlobalX.Hypermedia.AspNetCore/GlobalX.Hypermedia.AspNetCore.csproj --include-source --include-symbols -o ../../nuget